server:
  port: 9999

spring:
  datasource:
    username: webUser
    password: "030323"
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    driver-class-name: oracle.jdbc.OracleDriver

  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.lantu: debug

#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-field: deleted
#      logic-not-delete-value: 0
#      logic-delete-value: 1
